import { Question } from "~/api/exam";

export const testQuestions: { [key in Question["model_id"]]?: Question[] } = {
  QORD3x2: [
    {
      orderedAnswer: true,
      level: 3,
      options: [
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "G",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "R",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "A",
          position: 2,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "D",
          position: 3,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "E",
          position: 4,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "L",
          position: 5,
          isCorrect: false,
        },
      ],
      description: "Audio: Complete a palavra MAGRA. Texto: MA _ _ _",
      id: 20,
      axis_code: "EA",
      model_id: "QORD3x2",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea10b_enunciado.mp3?alt=media&token=b1316c35-0369-4387-8406-fbdd0e074e6e",
          file_name: "EA10B_Enunciado.mp3",
          description: "Audio: Complete a palavra MAGRA. Texto: MA _ _ _",
          position: 1,
          placeholder: "",
          type: "AUDIO",
        },
        {
          file_url: null,
          file_name: "",
          description: "MA___",
          position: 3,
          placeholder: "",
          type: "TEXT",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fmenina_magra.svg?alt=media&token=1aa72d84-cb97-498d-b774-9086cd37efea",
          file_name: "menina_magra",
          description: "imagem menina magra",
          position: 4,
          placeholder: "",
          type: "IMAGE",
        },
      ],
      category: "B",
      school_year: 2,
      multiplesAnswer: false,
      order: 10,
    },
  ],
  MODEL2: [
    {
      orderedAnswer: true,
      level: 1,
      options: [
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_letra_f.mp3?alt=media&token=bff2b1be-cf4f-4514-b1a8-0722ac887b0a",
          image_url: null,
          sound_name: "Alt_Letra_F.mp3",
          description: "F",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_letra_g.mp3?alt=media&token=f22ae8bc-ea18-4908-9879-7a5bac370cc4",
          image_url: null,
          sound_name: "Alt_Letra_G.mp3",
          description: "G",
          position: 2,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_letra_e.mp3?alt=media&token=dd35bdae-ff12-4019-8a49-c45fe73f9eb4",
          image_url: null,
          sound_name: "Alt_Letra_E.mp3",
          description: "E",
          position: 0,
          isCorrect: true,
        },
      ],
      description: "Organize as letras em ordem alfabética.",
      id: 3,
      axis_code: "EA",
      model_id: "MODEL2",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fvideo%2Fea2ab_enunciado.mp4?alt=media&token=8cb1c41d-7638-434f-85d5-74aea5d637cc",
          file_name: "EA2AB_Enunciado.mp4",
          description: "Organize as letras em ordem alfabética.",
          position: 2,
          placeholder: "",
          type: "VIDEO",
        },
      ],
      category: "A",
      school_year: 0,
      multiplesAnswer: false,
      order: 2,
    },
  ],
  MODEL18: [
    {
      orderedAnswer: true,
      level: 3,
      options: [
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "B",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "R",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "A",
          position: 2,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "P",
          position: 3,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "O",
          position: 4,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "L",
          position: 5,
          isCorrect: false,
        },
      ],
      description: "Audio: Complete a palavra CABRA. Texto: CA _ _ _",
      id: 19,
      axis_code: "EA",
      model_id: "MODEL18",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea10a_enunciado.mp3?alt=media&token=8e30ce20-0d7d-438f-9d6d-cd4da0379014",
          file_name: "EA10A_Enunciado.mp3",
          description: "Audio: Complete a palavra CABRA. Texto: CA _ _ _",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
        {
          file_url: null,
          file_name: "",
          description: "CA___",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: null,
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fcabra.svg?alt=media&token=3f563142-d435-4229-a19b-d6f0ec452558",
          file_name: "cabra",
          description: "imagem cabra",
          position: 4,
          placeholder: "",
          type: "IMAGE",
          classification: null,
        },
      ],
      category: "A",
      school_year: 2,
      multiplesAnswer: false,
      order: 10,
    },
  ],
  QME2x2Audio: [
    {
      orderedAnswer: false,
      level: 1,
      options: [
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_alternativa1.mp3?alt=media&token=9cf3d298-e2af-4afe-b423-085e047285ea",
          image_url: null,
          sound_name: "lct3b_alternativa1.mp3",
          description: "Porque a casa não tinha parede.",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_alternativa2.mp3?alt=media&token=e73fd2f4-939f-4471-b0e8-12953479f748",
          image_url: null,
          sound_name: "lct3b_alternativa2.mp3",
          description: "Porque a casa era engraçada.",
          position: 1,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3a_alternativa3.mp3?alt=media&token=45d5fbb9-c5b3-4d92-bd14-a21088655f06",
          image_url: null,
          sound_name: "lct3a_alternativa3.mp3",
          description: "Porque a casa era na Rua dos Bobos.",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_alternativa4.mp3?alt=media&token=728ddd68-dd59-4a86-b751-6051046842c2",
          image_url: null,
          sound_name: "lct3b_alternativa4.mp3",
          description: "Porque a casa era no número zero.",
          position: 3,
          isCorrect: false,
        },
      ],
      description:
        'Após ouvir a música, perguntar: "Por que não podia dormir na rede?"',
      id: 70,
      axis_code: "LC",
      model_id: "QME2x2Audio",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_enunciado.mp3?alt=media&token=9b39057d-b0f7-4dec-9e1e-f2059a95e8e0",
          file_name: "lct3b_enunciado.mp3",
          description:
            'Após ouvir a música, perguntar: "Por que não podia dormir na rede?"',
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: "ENUNCIADO",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3ab_texto.mp3?alt=media&token=e9a76051-8442-4553-b78a-99a321902ed0",
          file_name: "lct3ab_texto.mp3",
          description: "musica",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: "HISTORIA",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Ftitle_silence.mp3?alt=media&token=e842f2aa-57f6-49a8-b4b8-b3e1b3538992",
          file_name: "title_silence.mp3",
          description: "",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: "INTRO",
        },
      ],
      category: "B",
      school_year: 1,
      multiplesAnswer: false,
      order: 5,
      progress: 77.63157894736842,
    },
  ],
};
