import { Question, QuestionTitleClassification } from "~/api/exam";

export const testQuestions: { [key in Question["model_id"]]?: Question[] } = {
  QORD3x2: [
    {
      orderedAnswer: true,
      level: 3,
      options: [
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "G",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "R",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "A",
          position: 2,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "D",
          position: 3,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "E",
          position: 4,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "L",
          position: 5,
          isCorrect: false,
        },
      ],
      description: "Audio: Complete a palavra MAGRA. Texto: MA _ _ _",
      id: 20,
      axis_code: "EA",
      model_id: "QORD3x2",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea10b_enunciado.mp3?alt=media&token=b1316c35-0369-4387-8406-fbdd0e074e6e",
          file_name: "EA10B_Enunciado.mp3",
          description: "Audio: Complete a palavra MAGRA. Texto: MA _ _ _",
          position: 1,
          placeholder: "",
          type: "AUDIO",
        },
        {
          file_url: null,
          file_name: "",
          description: "MA___",
          position: 3,
          placeholder: "",
          type: "TEXT",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fmenina_magra.svg?alt=media&token=1aa72d84-cb97-498d-b774-9086cd37efea",
          file_name: "menina_magra",
          description: "imagem menina magra",
          position: 4,
          placeholder: "",
          type: "IMAGE",
        },
      ],
      category: "B",
      school_year: 2,
      multiplesAnswer: false,
      order: 10,
    },
    {
      orderedAnswer: true,
      level: 2,
      options: [
        {
          image_name: "escrita_ra",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_ra.svg?alt=media&token=842a5503-b055-434d-8211-830222d62997",
          sound_name: "",
          description: "",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "escrita_to",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_to.svg?alt=media&token=7c1aa70a-c786-417c-b924-87e0cfb3dd51",
          sound_name: "",
          description: "",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "escrita_ta",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_ta.svg?alt=media&token=cb4ace3d-f61b-4da1-8060-2b7ba5347995",
          sound_name: "",
          description: "",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "escrita_pa",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_pa.svg?alt=media&token=410171f9-07c3-47f1-aebe-189ae3bf0445",
          sound_name: "",
          description: "",
          position: 3,
          isCorrect: false,
        },
        {
          image_name: "escrita_ro",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_ro.svg?alt=media&token=59c3b849-2fb1-4525-8dad-21d9642c246a",
          sound_name: "",
          description: "",
          position: 4,
          isCorrect: false,
        },
        {
          image_name: "escrita_ma",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_ma.svg?alt=media&token=2f0a5ea9-74b2-48aa-886f-a7f3c46ba7de",
          sound_name: "",
          description: "",
          position: 5,
          isCorrect: false,
        },
      ],
      description:
        "A palavra NOTA é formada por dois pedaços NO - TA. Quais dois pedaços formam a palavra RATO?",
      id: 17,
      axis_code: "EA",
      model_id: "QORD3x2",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea9a_enunciado.mp3?alt=media&token=36769841-6813-4625-92e2-541905bab771",
          file_name: "EA9A_Enunciado.mp3",
          description:
            "A palavra NOTA é formada por dois pedaços NO - TA. Quais dois pedaços formam a palavra RATO?",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
      ],
      category: "A",
      school_year: 1,
      multiplesAnswer: false,
      order: 7,
    },
    {
      orderedAnswer: true,
      level: 2,
      options: [
        {
          image_name: "escrita_sa",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_sa.svg?alt=media&token=53461055-dd74-47b5-8765-af3388129c02",
          sound_name: "",
          description: "",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "escrita_no",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_no.svg?alt=media&token=93181618-c457-4a54-9da2-2ba6be5cd1a1",
          sound_name: "",
          description: "",
          position: 5,
          isCorrect: false,
        },
        {
          image_name: "escrita_to",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_to.svg?alt=media&token=c7596280-62f3-4129-ab3b-54e1a4eaab5a",
          sound_name: "",
          description: "",
          position: 3,
          isCorrect: false,
        },
        {
          image_name: "escrita_ra",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_ra.svg?alt=media&token=fdf7c728-37c3-4659-945a-c392d38495db",
          sound_name: "",
          description: "",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "escrita_po",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_po.svg?alt=media&token=ece23949-979c-4cf6-95f8-41a0f44d5445",
          sound_name: "",
          description: "",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "escrita_so",
          sound_url: null,
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fescrita_so.svg?alt=media&token=dca0d18b-2c82-41e1-acd5-d938cc211195",
          sound_name: "",
          description: "",
          position: 4,
          isCorrect: false,
        },
      ],
      description:
        "A palavra MATO é formada por dois pedaços MA - TO. Quais dois pedaços formam a palavra SAPO?",
      id: 18,
      axis_code: "EA",
      model_id: "QORD3x2",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea9b_enunciado.mp3?alt=media&token=08182567-98b2-4084-8de4-924d76478fd2",
          file_name: "EA9B_Enunciado.mp3",
          description:
            "A palavra MATO é formada por dois pedaços MA - TO. Quais dois pedaços formam a palavra SAPO?",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
      ],
      category: "B",
      school_year: 1,
      multiplesAnswer: false,
      order: 7,
      progress: 26.32,
    },
  ],
  MODEL2: [
    {
      orderedAnswer: true,
      level: 1,
      options: [
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_letra_f.mp3?alt=media&token=bff2b1be-cf4f-4514-b1a8-0722ac887b0a",
          image_url: null,
          sound_name: "Alt_Letra_F.mp3",
          description: "F",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_letra_g.mp3?alt=media&token=f22ae8bc-ea18-4908-9879-7a5bac370cc4",
          image_url: null,
          sound_name: "Alt_Letra_G.mp3",
          description: "G",
          position: 2,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_letra_e.mp3?alt=media&token=dd35bdae-ff12-4019-8a49-c45fe73f9eb4",
          image_url: null,
          sound_name: "Alt_Letra_E.mp3",
          description: "E",
          position: 0,
          isCorrect: true,
        },
      ],
      description: "Organize as letras em ordem alfabética.",
      id: 3,
      axis_code: "EA",
      model_id: "MODEL2",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fvideo%2Fea2ab_enunciado.mp4?alt=media&token=8cb1c41d-7638-434f-85d5-74aea5d637cc",
          file_name: "EA2AB_Enunciado.mp4",
          description: "Organize as letras em ordem alfabética.",
          position: 2,
          placeholder: "",
          type: "VIDEO",
        },
      ],
      category: "A",
      school_year: 0,
      multiplesAnswer: false,
      order: 2,
    },
  ],
  MODEL18: [
    {
      orderedAnswer: true,
      level: 3,
      options: [
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "B",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "R",
          position: 1,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "A",
          position: 2,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "P",
          position: 3,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "O",
          position: 4,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "L",
          position: 5,
          isCorrect: false,
        },
      ],
      description: "Audio: Complete a palavra CABRA. Texto: CA _ _ _",
      id: 19,
      axis_code: "EA",
      model_id: "MODEL18",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea10a_enunciado.mp3?alt=media&token=8e30ce20-0d7d-438f-9d6d-cd4da0379014",
          file_name: "EA10A_Enunciado.mp3",
          description: "Audio: Complete a palavra CABRA. Texto: CA _ _ _",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
        {
          file_url: null,
          file_name: "",
          description: "CA___",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: null,
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fcabra.svg?alt=media&token=3f563142-d435-4229-a19b-d6f0ec452558",
          file_name: "cabra",
          description: "imagem cabra",
          position: 4,
          placeholder: "",
          type: "IMAGE",
          classification: null,
        },
      ],
      category: "A",
      school_year: 2,
      multiplesAnswer: false,
      order: 10,
    },
  ],
  QME2x2Audio: [
    {
      orderedAnswer: false,
      level: 1,
      options: [
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_alternativa1.mp3?alt=media&token=9cf3d298-e2af-4afe-b423-085e047285ea",
          image_url: null,
          sound_name: "lct3b_alternativa1.mp3",
          description: "Porque a casa não tinha parede.",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_alternativa2.mp3?alt=media&token=e73fd2f4-939f-4471-b0e8-12953479f748",
          image_url: null,
          sound_name: "lct3b_alternativa2.mp3",
          description: "Porque a casa era engraçada.",
          position: 1,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3a_alternativa3.mp3?alt=media&token=45d5fbb9-c5b3-4d92-bd14-a21088655f06",
          image_url: null,
          sound_name: "lct3a_alternativa3.mp3",
          description: "Porque a casa era na Rua dos Bobos.",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_alternativa4.mp3?alt=media&token=728ddd68-dd59-4a86-b751-6051046842c2",
          image_url: null,
          sound_name: "lct3b_alternativa4.mp3",
          description: "Porque a casa era no número zero.",
          position: 3,
          isCorrect: false,
        },
      ],
      description:
        'Após ouvir a música, perguntar: "Por que não podia dormir na rede?"',
      id: 70,
      axis_code: "LC",
      model_id: "QME2x2Audio",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3b_enunciado.mp3?alt=media&token=9b39057d-b0f7-4dec-9e1e-f2059a95e8e0",
          file_name: "lct3b_enunciado.mp3",
          description:
            'Após ouvir a música, perguntar: "Por que não podia dormir na rede?"',
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: "ENUNCIADO",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct3ab_texto.mp3?alt=media&token=e9a76051-8442-4553-b78a-99a321902ed0",
          file_name: "lct3ab_texto.mp3",
          description: "musica",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: "HISTORIA",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Ftitle_silence.mp3?alt=media&token=e842f2aa-57f6-49a8-b4b8-b3e1b3538992",
          file_name: "title_silence.mp3",
          description: "",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: "INTRO",
        },
      ],
      category: "B",
      school_year: 1,
      multiplesAnswer: false,
      order: 5,
      progress: 77.63157894736842,
    },
  ],
  MODEL4: [
    {
      orderedAnswer: false,
      level: 1,
      options: [
        {
          image_name: "pato",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_pato.mp3?alt=media&token=e553b2ca-9c96-4ab7-a05a-05d4e8d240ef",
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fpato.svg?alt=media&token=ee3e41bb-3d63-4742-b066-b2889064423b",
          sound_name: "Alt_Pato.mp3",
          description: "Imagem de um pato",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "rato",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_rato.mp3?alt=media&token=efc636d8-6576-4fb4-b0c1-6cebf4d912f3",
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Frato.svg?alt=media&token=08fe63e6-79ca-41b1-80ac-cae27e348413",
          sound_name: "Alt_Rato.mp3",
          description: "Imagem de um rato",
          position: 1,
          isCorrect: false,
        },
        {
          image_name: "bola",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_bola.mp3?alt=media&token=a78ba957-53a1-4794-95ac-c984e9b45fff",
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fbola.svg?alt=media&token=6f8e8384-0bd9-4ec5-8b08-078b27bcec3f",
          sound_name: "Alt_Bola.mp3",
          description: "Imagem de um bola",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "casa",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Falt_casa.mp3?alt=media&token=bec80efc-88a9-4411-b7b2-b4cfcb046ae8",
          image_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fcasa.svg?alt=media&token=85effb0d-c7cf-429e-8a5f-af78ab0d4956",
          sound_name: "Alt_Casa.mp3",
          description: "Imagem de uma casa",
          position: 3,
          isCorrect: false,
        },
      ],
      description: "Audio: Qual figura começa com a letra P? Imagem: P",
      id: 7,
      axis_code: "EA",
      model_id: "MODEL4",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Fea4a_enunciado.mp3?alt=media&token=b8f37904-c0bf-4211-ae51-7f1c37d3674b",
          file_name: "EA4A_Enunciado.mp3",
          description: "Audio: Qual figura começa com a letra P? Imagem: P",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
        {
          file_url: null,
          file_name: "",
          description:
            "<h1><b>QUAL FIGURA COMEÇA COM A LETRA <font color='#47CDFF'><u>P</u></font>?</b></h1>",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: null,
        },
      ],
      category: "A",
      school_year: 0,
      multiplesAnswer: false,
      order: 1,
      progress: 315,
    },
  ],
  "MODEL8-PROVA": [
    {
      orderedAnswer: false,
      level: 1,
      options: [
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct4a_alternativa1.mp3?alt=media&token=905fcb1e-7e17-426c-9aa0-a2cd48554f1e",
          image_url: null,
          sound_name: "lct4a_alternativa1.mp3",
          description: "Porque ela queria comer a maçã.",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct4a_alternativa2.mp3?alt=media&token=54616e1d-ce4b-41e7-a598-80316eb755fd",
          image_url: null,
          sound_name: "lct4a_alternativa2.mp3",
          description: "Porque ela queria olhar a maçã.",
          position: 1,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct4a_alternativa3.mp3?alt=media&token=7e6a5a6d-cf90-4088-b05a-8e9d0cd5c0e6",
          image_url: null,
          sound_name: "lct4a_alternativa3.mp3",
          description: "Porque ela estava procurando uma minhoca.",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct4a_alternativa4.mp3?alt=media&token=9b6442ff-6a18-41f5-bd8d-b7c560f0d888",
          image_url: null,
          sound_name: "lct4a_alternativa4.mp3",
          description: "Porque ela estava triste.",
          position: 3,
          isCorrect: false,
        },
      ],
      description: "Por que a menina pegou a maçã da árvore?",
      id: 71,
      axis_code: "LC",
      model_id: "MODEL8-PROVA",
      titles: [
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Flc4ab.png?alt=media&token=6fccb655-5e33-4154-b453-021e14052875",
          file_name: "lc4ab",
          description: "Por que a menina pegou a maçã da árvore?",
          position: 4,
          placeholder: "",
          type: "IMAGE",
          classification: null,
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct4a_enunciado.mp3?alt=media&token=99bf28f7-4f3e-4b21-9bdd-57397f5185f1",
          file_name: "lct4a_enunciado.mp3",
          description: "Por que a menina pegou a maçã da árvore?",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
      ],
      category: "A",
      school_year: 0,
      multiplesAnswer: false,
      order: 4,
      progress: 34.21,
    },
  ],
  QME2x2Text: [
    {
      orderedAnswer: false,
      level: 3,
      options: [
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ele respira fora d'água.",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ele gosta da terra.",
          position: 1,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ele bota ovo.",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ele respira dentro d'água.",
          position: 3,
          isCorrect: false,
        },
      ],
      description:
        "<b>A vida dos sapos</b><br />Os sapos têm quatro fases de vida. Em cada fase, eles crescem e mudam. Os sapos botam ovos. O bebê sapo se chama girino. O girino mora na água e respira embaixo d’água. Girinos não têm pernas. Quando o sapo cresce, ele respira fora d’água e pode viver na terra.",
      id: 86,
      axis_code: "LC",
      model_id: "QME2x2Text",
      titles: [
        {
          file_url: null,
          file_name: "",
          description:
            "<b>A vida dos sapos</b><br />Os sapos têm quatro fases de vida. Em cada fase, eles crescem e mudam. Os sapos botam ovos. O bebê sapo se chama girino. O girino mora na água e respira embaixo d’água. Girinos não têm pernas. Quando o sapo cresce, ele respira fora d’água e pode viver na terra.",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: "HISTORIA",
        },
        {
          file_url: null,
          file_name: "",
          description: "Por que o sapo pode viver na terra quando cresce?",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: "ENUNCIADO",
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Fimage%2Fsapo.svg?alt=media&token=4b4c8d36-06c3-472e-adf4-2e490b122750",
          file_name: "sapo",
          description: "",
          position: 4,
          placeholder: "",
          type: "IMAGE",
          classification: null,
        },
      ],
      category: "B",
      school_year: 2,
      multiplesAnswer: false,
      order: 13,
    },
  ],
  MODEL32: [
    {
      orderedAnswer: false,
      level: 4,
      options: [
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ela não conseguiu pegar as uvas.",
          position: 0,
          isCorrect: true,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ela não gostava de uvas.",
          position: 1,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque ela estava com fome.",
          position: 2,
          isCorrect: false,
        },
        {
          image_name: "",
          sound_url: null,
          image_url: null,
          sound_name: "",
          description: "Porque as uvas ainda não estavam maduras.",
          position: 3,
          isCorrect: false,
        },
      ],
      description:
        "<h1>A RAPOSA E A UVA</h1><br/>Era uma vez uma raposa que estava sem comer havia muitos dias. Ela foi passear no pomar e encontrou um lindo cacho de uvas.<br/><br/>O cacho estava no alto de uma parreira, e a raposa decidiu se esforçar para apanhá-lo. Ela deu muitos pulos para tentar alcançar, mas, depois de muitas tentativas, ficou exausta e continuava faminta. Então, a raposa deu de ombros e resolveu ir embora.<br/><br/>Desapontada, a raposa disse:<br/><br/>— Estas uvas estão verdes mesmo... Nem quero mais comê-las.",
      id: 90,
      axis_code: "LC",
      model_id: "MODEL32",
      titles: [
        {
          file_url: null,
          file_name: "",
          description:
            "<h1>A RAPOSA E A UVA</h1><br/>Era uma vez uma raposa que estava sem comer havia muitos dias. Ela foi passear no pomar e encontrou um lindo cacho de uvas.<br/><br/>O cacho estava no alto de uma parreira, e a raposa decidiu se esforçar para apanhá-lo. Ela deu muitos pulos para tentar alcançar, mas, depois de muitas tentativas, ficou exausta e continuava faminta. Então, a raposa deu de ombros e resolveu ir embora.<br/><br/>Desapontada, a raposa disse:<br/><br/>— Estas uvas estão verdes mesmo... Nem quero mais comê-las.",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: QuestionTitleClassification.HISTORIA,
        },
        {
          file_url: null,
          file_name: "",
          description: "Por que a raposa disse que as uvas estavam verdes?",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: QuestionTitleClassification.ENUNCIADO,
        },
        {
          file_url:
            "https://firebasestorage.googleapis.com/v0/b/eduedu-escola-hub---stg.appspot.com/o/exam%2Faudio%2Flct14b_enunciado.mp3?alt=media&token=bdbcbc7a-ffc1-4a52-9a46-fb45522cbfa2",
          file_name: "lct14b_enunciado.mp3",
          description: "intro",
          position: 1,
          placeholder: "",
          type: "AUDIO",
          classification: null,
        },
        {
          file_url: null,
          file_name: "",
          description: "Leia a fábula e responda à pergunta.",
          position: 3,
          placeholder: "",
          type: "TEXT",
          classification: QuestionTitleClassification.INTRO,
        },
      ],
      category: "B",
      school_year: 3,
      multiplesAnswer: false,
      order: 14,
    },
  ],
};
