name: DEVELOPMENT - E2E Test Pipeline

on: 
  workflow_run:
    workflows: ["DEVELOPMENT - CI/CD Pipeline"]
    types:
    - completed

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      APP_DEBUG_URL: ${{ secrets.APP_DEBUG_URL }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: E2E Test Run
        run: |
          yarn install
          yarn test:models
      
      - name: Send Error Message
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#ff0000"
          username: "GitHub Bot"
          avatar_url: https://i.imgur.com/Kvn45ev.png
          message: Portal Aluno | Teste E2E contém inconsistências... | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job_id }}
